name: blood_donation
description: "A new Flutter project."
publish_to: "none"
version: 0.1.5+027


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base
  animations: ^2.0.11
  # auto_route: ^9.2.2
  dio: ^5.7.0 
  flutter_localization: ^0.2.2
  flutter_screenutil: ^5.9.3
  flutter_toastr: ^1.0.3
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.4
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  logger: ^2.4.0
  path_provider: ^2.1.4
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  toastification: ^2.2.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.10+1
  coupon_uikit: ^0.2.1
  board_datetime_picker: ^2.1.3
  animated_custom_dropdown: ^3.1.1
  collection: ^1.18.0
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^3.1.2
  fl_chart: ^0.69.0
  retrofit: ^4.4.1
  retrofit_generator: ^8.2.1
  animated_background: ^2.0.0
  flutter_carousel_widget: ^3.0.1
  flutter_smart_dialog: ^4.9.8+2
  form_builder_validators: ^11.0.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3 
  firebase_core: ^3.8.0 
  firebase_messaging: ^15.1.5
  firebase_core_platform_interface: ^5.0.0
  flutter_local_notifications: ^17.2.3
  # google_sign_in: ^6.2.1
  jwt_decoder: ^2.0.1
  auto_size_text: ^3.0.0 
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  get: ^4.6.6
  flutter_easyloading: ^3.0.5 
  uuid: ^4.5.1
  device_info_plus: ^10.1.2
  android_id: ^0.4.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.4.2
  pin_code_fields: ^8.0.1
  encrypt: 5.0.3
  crypto: 3.0.5
  photo_view: 0.15.0
  dotted_border: ^2.1.0
  qr_code_scanner: ^1.0.1
  in_app_review: ^2.0.10 
  ticker_text: ^2.1.0
  enhance_expansion_panel: 0.7.0
  pull_to_refresh_flutter3: ^2.0.2
  screen_brightness: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Base
  injectable_generator: ^2.6.2
  # auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11


flutter:
  uses-material-design: true

  assets:
    - pubspec.yaml
    - assets/images/
    - assets/images/auth_options/
    - assets/icons/ 

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
